version: '3.1'

services:
    postgres:
        image: postgres:9.6.5-alpine
        ports:
          - 5442:5432
        restart: always
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_USER: username
            POSTGRES_DB: target
    mongo:
        image: mongo:3.5.13-jessie
        restart: always
        ports:
            - 27017:27017
        volumes:
          - ./docker/001_init-rs.js:/docker-entrypoint-initdb.d/001_init-rs.js
        command: 'docker-entrypoint.sh mongod --replSet singleNodeRepl --bind_ip_all'